apiVersion: v2
name: zrok2
description: Run the zrok2 controller and zrok2 frontend components as a K8s deployment

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0-pre1

# This is the version number of the application being deployed.
appVersion: 2.0.0-rc8

dependencies: []
