clientApi:
  altDnsNames:
    - ""  # client.ziti.example.com

webBindingPki:
  altServerCerts:
    - mode: certManager
      secretName: ziti-controller-alt-server-cert1
      dnsNames:
        # ensure the DNS SAN matches altDnsNames
        - "{{ .Values.clientApi.altDnsNames[0] }}"
      issuerRef:
        group: cert-manager.io
        # ClusterIssuer or Issuer
        kind: ClusterIssuer
        # some cert-manager issuer that can solve ACME challenges for the requested DNS SAN
        name: cloudflare-dns01-issuer-prod
      mountPath: /etc/ziti/ziti-controller-alt-server-cert1
