apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ziti-edge-tunnel.fullname" . }}-identity-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
