apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ziti-edge-tunnel.fullname" . }}-identity-migrate
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "ziti-edge-tunnel.fullname" . }}-identity-migrate
  apiGroup: rbac.authorization.k8s.io
