---
{{ if and (.Values.zitiIdentity) (not .Values.secret.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ziti-edge-tunnel.fullname" . }}-identity
type: Opaque
data:
  persisted-identity: {{ .Values.zitiIdentity | b64enc }}
{{ end }}
