apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ziti-host.fullname" . }}-identity-migrate
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "delete"]
