apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zrok2.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "zrok2.fullname" . }}-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - {{ include "zrok2.fullname" . }}-frontend-identity
      - {{ include "zrok2.fullname" . }}-dpc-identity
      - {{ include "zrok2.fullname" . }}-ziggy-account-token
    verbs: ["get", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "zrok2.fullname" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "zrok2.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "zrok2.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
