
# minimal input values for ingress-nginx; to enable tls, add cert manager issuer annotation and tls.secretName to each ingress dict

controller:
  ingress:
    enabled: true
    scheme: http
    className: nginx
    # annotations:
    #   cert-manager.io/cluster-issuer: cloudflare-dns-issuer-prod
    # tls:
    #   secretName: zrok-api-tls

frontend:
  ingress:
    enabled: true
    scheme: http
    className: nginx
    # annotations:
    #   cert-manager.io/cluster-issuer: cloudflare-dns-issuer-prod
    # tls:
    #   secretName: zrok-wildcard-tls
