name: Deploy README to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - README.md

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install pandoc
        shell: bash
        run: |
          set -o pipefail
          set -o xtrace
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Prepare file for deployment
        shell: bash
        run: |
          set -o pipefail
          set -o xtrace
          rm -rf ./public
          mkdir -p ./public
          # Convert README.md (GitHub-flavored Markdown) to a standalone HTML page
          pandoc -f gfm -t html5 -s ./README.md -o ./public/index.html
          echo "Staged files:" && find ./public -type f -ls || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          keep_files: true
