name: Deploy README to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - README.md

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Prepare file for deployment
        shell: bash
        run: |
          set -o pipefail
          set -o xtrace
          mkdir -p ./public
          cp ./README.md ./public/index.md
          cp ./_config.yml ./public/_config.yml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          keep_files: true
