name: Release Notes Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

# Set default permissions as read only
permissions: read-all

jobs:
  release-notes-labeler:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # GitHub's release notes generator uses these labels to select PRs to include
      - name: Label Pull Request by Changed Charts
        uses: actions/labeler@v6.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
