name: Release Notes Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

# Set default permissions as read only
permissions: read-all

jobs:
  release-notes-labeler:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # GitHub's release notes generator uses these lables to select PRs to include
      - name: Label Pull Request by Changed Charts
        id: labeler
        uses: maxisam/changed-files-labeler@v0.1.1
        with:
            authToken: ${{ secrets.GITHUB_TOKEN }}
            basePaths: charts
            prefixes: notes|skip
            includedGlob: ""  # no filter
            debugShowPaths: true
            layers: 1

      - name: Debug Labeler
        run: |
          echo "Labels: ${{ steps.labeler.outputs.labels }}"
          echo "Paths: ${{ steps.labeler.outputs.paths }}"
          echo "Changed: ${{ steps.labeler.outputs.changed }}"
